mode: difference
loglevel: info

limit: 50000
ratelimit: 4

storage: sqlite
output_dir: ./runs

masterdsn: "postgres://USER:PASS@HOST:PORT/demo?sslmode=disable"
slavedsn: "postgres://USER:PASS@HOST:PORT/demo?sslmode=disable"

max_open_conns_master: 4
max_open_conns_slave: 1

master_sql_files:
  - ./sql/master/1.sql
  - ./sql/master/2.sql

slave_sql_file: ./sql/slave/Slave.sql

sqlite_path: work/compare.db
sqlite_busy_timeout_ms: 5000
sqlite_cache_size_kb: 65536
sqlite_mmap_size_mb: 256
sqlite_write_batch: 20000
sqlite_result_fetch_size: 50000
sqlite_temp_store: FILE
sqlite_synchronous: NORMAL
sqlite_journal_mode: WAL
sqlite_keep_db: false
sqlite_run_analyze: false
sqlite_vacuum_on_finish: false

sqlite_extra_pragmas:
  - "PRAGMA wal_autocheckpoint = 1000;"
  - "PRAGMA cache_spill = ON;"