mode: "difference"  #"difference" / "intersection"
#important for difference mode, working as "master set MINUS slave set"
masterdsn: #"oracle://<login>:<password>@<host>:<port>/<sid>" #first DB
slavedsn: #"postgresql://<login>:<password>@<host>:<port>/<sid>" #second DB
loglevel: "error" # "error" "info" "debug"
limit: 50000
ratelimit: 5
mastersql: "./Master/"
slavesql: "./Slave.sql"